DROP TABLE Voter1 CASCADE CONSTRAINTS;
CREATE TABLE Voter1 AS
SELECT *
FROM Voter
WHERE VGender = 'Male';
commit;
select * from Voter1;

CREATE OR REPLACE TRIGGER Voter1Trigger_after_insert
AFTER INSERT
ON Voter1
BEGIN
   DBMS_OUTPUT.PUT_LINE('VALUES INSERTED INTO Voter1 TABLE');
END;
/
CREATE OR REPLACE TRIGGER Voter1Trigger_after_update
AFTER Update
ON Voter1
BEGIN
   DBMS_OUTPUT.PUT_LINE('VALUES UPDATED INTO Voter1 TABLE');
END;
/
